
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    container_name: mc-manager-app
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      - db
    environment:
      - MONGO_URI=${MONGO_URI}
      
    networks:
      - mcnet

  db:
    image: mongo:7.0.15
    container_name: mc-manager-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "cdevries"
      MONGO_INITDB_ROOT_PASSWORD: "0nly4Connor!"
      MONGO_INITDB_DATABASE: "mcmanager"
    
    ports:
      - "41017:27017"
    volumes:
      - dbdata:/data
      - ../db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - mcnet

networks:
  mcnet:

volumes:
  dbdata: